"""
6-7 compute all mnemonics for a phone number

0. T
given a phone num in string, return all possible char sequences

1. C
how to access char sequence per number?

2. EX
2276696 to ACRONYM, ABPOMZN, ...

3. BF
iterative
for s in current list
    for char in cur number
        generate combination
        append
replace

=> messy, not reusable

4. Qs
- recursive?

- not dependent on length of str?

- how to recurse?
123 -> 23 -> 3
let ret value be list of all acry generated by digits.
make new list in for loop.

- Base?
if len of num string is 1.
return 3 chars.

- how to map num to chars?
num to list of chars.

5. Outline
def helper(numstr):
    if len(numstr) == 1:
        ret map[numstr]
    ret = []
    tmp = helper(numstr[1:])
    for acry in tmp:
        for c in map[numstr]
            ret.append(c + acry)

    ret ret
"""



            
        

